version: "3.8"

services:
  it-automation:
    image: ghcr.io/exastro-suite/it-automation:1.10.0-ja-ubi8
    privileged: true
    extra_hosts:
      - "exastro-it-automation:127.0.0.1"
    ports:
      - "8080:80"
    volumes:
      - database:/exastro-database-volume
      - file:/exastro-file-volume

  target:
    build: ./test-ssh-server
    image: test-ssh-server:1.0.0
    privileged: true

volumes:
  database:
  file:
